### ISSUE TITLE
SublimeAVR: could not find ave-gcc

### ISSUE THREAD

**Issue by snikrepmada** [kblomqvist/SublimeAVR#4]
I have this as my $PATH and it still will not work.  What am I doing wrong any help would be great. Thanks Adam.

/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Applications/microchip/xc32/v1.20/bin:/Applications/microchip/xc16/v1.11/bin:/Applications/microchip/xc8/v1.12/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/usr/texbin

**Comment by ottoragam** [comment]
Hi, I'm using Windows 7 and Sublime Text 2. My toolchain was installed via WinAVR, which automatically updates the system variables with the pertinent content. I checked the variable Path and it does indeed contain "C:\WinAVR-20100110\bin", the directory for the avr-gcc binary. Still, when I try to create a project, i receive the message "could not find avr-gcc". Any ideas on what could be wrong?

**Comment by kblomqvist** [comment]
You have set ``C:\WinAVR-20100110\bin`` in environment path (Windows global setting) or in plugin settings? If it's in environment path, then please recheck that you can call ``avr-gcc`` in command prompt.

I'm not able to reproduces the issue and it confuses me that this doesn't seem to work in all systems.

**Comment by ottoragam** [comment]
Yep, I've set the C:\WinAVR-20100110\bin in enviroment path, and I can call avr-gcc from the command prompt. Heres the pictures:

![winavr](https://cloud.githubusercontent.com/assets/8891812/7543270/cfb6d012-f588-11e4-88b9-11315a90df0b.png)
![path](https://cloud.githubusercontent.com/assets/8891812/7543273/d2781afe-f588-11e4-90eb-a62c09756d7b.png)
![sublime](https://cloud.githubusercontent.com/assets/8891812/7543274/d480db2e-f588-11e4-8f2f-6bcf1a0f5333.png)
![cmd](https://cloud.githubusercontent.com/assets/8891812/7543276/d60603ca-f588-11e4-8856-8161c54c0719.png)

**Comment by kblomqvist** [comment]
Could you edit ``unix.py`` file https://github.com/kblomqvist/SublimeAVR/blob/master/unix.py#L28 and print ``target`` to ST2 console so that we can debug this further.

**Comment by ottoragam** [comment]
Sure, just give a few hours (I'm away from Pc right now). Thanks for the help!

**Comment by ottoragam** [comment]
Hi again. I'm not sure if I understood the code. I supposed that the function attempted to get every directory listed in the PATH variable, and append to each one of them the file I'm searching for to see if it exist in said directoires. So I used avr-gcc as the function input, but nothing happened; the for loop in the function does nothing because the argument path is an empty string, is this right?

**Comment by kblomqvist** [comment]
Argument path is an extension to ``environ['PATH']``. So if the argument path is empty then your ``avr-gcc`` should be found from ``C:\WinAVR-20100110\bin``.

**Comment by ottoragam** [comment]
Something is wrong with the string splitting. It only returns [''] even when environ['PATH'] is non empty. I did the following:

![which](https://cloud.githubusercontent.com/assets/8891812/7549604/324f5342-f602-11e4-8f8e-44153e2e6e4e.png)

**Comment by ottoragam** [comment]
I added C:/WinAVR-20100110/bin into the plugin default settings and the "Could not find avr-gcc" message dissapeared (note that i used "/" instead of the default backslash). The thing is the create project command does nothing afterwards.

**Comment by kblomqvist** [comment]
For some reason, most likely because your avr-gcc version is working differently, the plugin cannot get  the list of MCU types.

You could check whether the list is empty or not:
https://github.com/kblomqvist/SublimeAVR/blob/master/SublimeAVR.py#L57

Also what do you get when you run ``avr-as -mlist-devices`` in command prompt?

**Comment by kblomqvist** [comment]
This should fix path splitting: https://github.com/kblomqvist/SublimeAVR/commit/c94adb2199a3dc4a9d9509535cf2f56c0411ce22

**Comment by ottoragam** [comment]
The fix worked. I do get "C:\WinAVR-20100110\bin" as output for avr-gcc's path. As for displaying the devices list on in command prompt...

![mcu-list](https://cloud.githubusercontent.com/assets/8891812/7553347/cf1e9582-f6b8-11e4-99f4-7330c3b4c0df.png)

Not sure what the last line means

**Comment by kblomqvist** [comment]
How about now with this change: https://github.com/kblomqvist/SublimeAVR/commit/4243e5dfc63eebcee1786432033b23ff7b8031cd

**Comment by ottoragam** [comment]
It is working now! Thanks for doing the changes to support my toolchain. At least now one has the option of using the WinAVR package (no idea why it is so outdated).

**Comment by kblomqvist** [comment]
Release v1.1.0 includes this fix: https://github.com/kblomqvist/SublimeAVR/releases/tag/1.1.0
